# ======= Default DOCKER IMAGE ===========
image: localhost:5000/spyglass_centos8
# =========== ALL THE STAGES ===========
# All the stages will be executed in this order
stages:
    - linting
    - sim

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

# =========== STAGE ===========
#   - linting
# =============================
linting_spyglass:
  image: localhost:5000/spyglass_centos8:latest
  stage: linting
  tags:
    - spyglass
  artifacts:
    paths:
      - ./ci/SafeDM_top/consolidated_reports/SafeDM_top_lint_lint_rtl/moresimple.rpt
    when: always
    expire_in: 30 days
  script:
    - echo "lint_spyglass"
    - make "docker_spyglass"    
  allow_failure: false

  # =========== STAGE ===========
#   - sim
# =============================
questa:
  image: localhost:5000/questa_ubuntu:latest
  stage: sim 
  tags:
    - questa 
  artifacts:
    paths:
      - ./ci/.questa.log
    when: always
    expire_in: 30 days
  script:
    - echo "Questa TB"
    - make "questa" 
  allow_failure: false